
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://siyfuzjwhfhdxuyzelol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpeWZ1emp3aGZoZHh1eXplbG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTk3MTMsImV4cCI6MjA4NzY5NTcxM30.jm9BQiQAhJmMvYiQAFiklTd3oPO9fcIOGqihEkEYoLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
